spring:
  redis:
    database: 0
    host: 192.168.56.10
    port: 6380
    lettuce:
      pool:
        max-active: 10
        ## always wait by default
        max-wait: -1
        max-idle: 10
        min-idle: 0