spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.56.10:3307/test
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/test_insert
      username: root
      password: wangyw123
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource